kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ledger
nodes:
- role: control-plane
  labels:
    ingress-ready: true
  extraPortMappings:
  - containerPort: 80
    hostPort: 50080
    protocol: TCP
  - containerPort: 443
    hostPort: 50443
    protocol: TCP
- role: worker
  labels:
    worker-type: app
- role: worker
  labels:
    worker-type: db
  extraPortMappings:
  - containerPort: 5432
    hostPort: 55432
    protocol: TCP
- role: worker
  labels:
    worker-type: beanstalkd
