kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ledger
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://ledger-worker:5000"]
nodes:
  - role: control-plane
    labels:
      ingress-ready: true
    extraPortMappings:
      - containerPort: 80
        hostPort: 50080
        protocol: TCP
  - role: worker
    labels:
      worker-type: beanstalkd
      registry: true # will have ledger-worker docker name
    extraPortMappings:
      - containerPort: 5000
        hostPort: 5000
        protocol: TCP
  - role: worker
    labels:
      worker-type: app
  - role: worker
    labels:
      worker-type: db
    extraPortMappings:
      - containerPort: 5432
        hostPort: 55432
        protocol: TCP
