ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - '**/*_spec.rb'

Metrics/ParameterLists:
  Max: 15 #I'm sorry but I have some and can not be fixed easily... :(
