ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'
