language: ruby
cache: bundler
rvm:
- 2.2
sudo: false
addons:
  postgresql: "9.3"
services:
  - docker
env: DB_CONFIG=config/database_postgres.yml
before_script:
  - psql -c 'create database ledger_dev;' -U postgres 
  - psql -c 'create database ledger_test;' -U postgres 
  - psql -c 'create database ledger_event_store;' -U postgres 
  - bundle exec rake db:setup
script: bundle exec rspec spec
after_success:
  - docker build -t evgenymyasishchev/ledger .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
  - docker push evgenymyasishchev/ledger