language: ruby
cache: bundler
rvm:
- 2.2
sudo: false
addons:
  postgresql: "9.3"
services:
  - docker
cache: bundler  
env: DB_CONFIG=config/database_postgres.yml
before_script:
  - psql -c 'create database ledger_dev;' -U postgres 
  - psql -c 'create database ledger_test;' -U postgres 
  - psql -c 'create database ledger_event_store;' -U postgres 
  - bundle exec rake db:setup
script: bundle exec rspec spec
after_success:
- ./docker/build-and-publish.sh -b docker -r ${TRAVIS_BRANCH} -n ${TRAVIS_BUILD_NUMBER} -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}