# Compose file is used to setup dev env. Prod env is deployed differently

version: '3.2'
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
      args:
        RAILS_ENV: 'development'
        DISABLE_SPRING: 'false'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - beanstalkd
    volumes:
      - ./:/apps/ledger/app
    environment:
      BEANSTALKD_URL: beanstalk://beanstalkd:11300

  db:
    image: postgres:9.5
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@my-ledger.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

  beanstalkd:
    build:
      context: ./docker
      dockerfile: Dockerfile.beanstalkd

