# Compose file is used to setup dev env. Prod env is deployed differently

version: '3.8'
services:
  app:
    image: localhost:5000/ledger:latest
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      beanstalkd:
        condition: service_started
    volumes:
      - ./:/apps/ledger/app
    environment:
      DATABASE_HOST: db
      BEANSTALKD_URL: beanstalk://beanstalkd:11300
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}

  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  beanstalkd:
    build:
      context: ./docker
      dockerfile: Dockerfile.beanstalkd

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./tmp/local-registry:/var/lib/registry

