# Compose file is used to setup dev env. Prod env is deployed differently

version: '3.2'
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
      args:
        RAILS_ENV: 'development'
        DISABLE_SPRING: 'false'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - beanstalkd
    volumes:
      - ./:/apps/ledger/app
    environment:
      DATABASE_HOST: db
      BEANSTALKD_URL: beanstalk://beanstalkd:11300
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}

  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: password

  beanstalkd:
    build:
      context: ./docker
      dockerfile: Dockerfile.beanstalkd

