apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_USER: postgres # local only password
  POSTGRES_PASSWORD: password # local only password