#
# Autogenerated file. Do not edit manually. Generated with CurrenciesUpdater.
#
Currency.register english_name: 'Afghani', alpha_code: 'AFN', numeric_code: 971
Currency.register english_name: 'Euro', alpha_code: 'EUR', numeric_code: 978
Currency.register english_name: 'Lek', alpha_code: 'ALL', numeric_code: 8
Currency.register english_name: 'Algerian Dinar', alpha_code: 'DZD', numeric_code: 12
Currency.register english_name: 'US Dollar', alpha_code: 'USD', numeric_code: 840
Currency.register english_name: 'Kwanza', alpha_code: 'AOA', numeric_code: 973
Currency.register english_name: 'East Caribbean Dollar', alpha_code: 'XCD', numeric_code: 951
Currency.register english_name: 'Argentine Peso', alpha_code: 'ARS', numeric_code: 32
Currency.register english_name: 'Armenian Dram', alpha_code: 'AMD', numeric_code: 51
Currency.register english_name: 'Aruban Florin', alpha_code: 'AWG', numeric_code: 533
Currency.register english_name: 'Australian Dollar', alpha_code: 'AUD', numeric_code: 36
Currency.register english_name: 'Azerbaijanian Manat', alpha_code: 'AZN', numeric_code: 944
Currency.register english_name: 'Bahamian Dollar', alpha_code: 'BSD', numeric_code: 44
Currency.register english_name: 'Bahraini Dinar', alpha_code: 'BHD', numeric_code: 48
Currency.register english_name: 'Taka', alpha_code: 'BDT', numeric_code: 50
Currency.register english_name: 'Barbados Dollar', alpha_code: 'BBD', numeric_code: 52
Currency.register english_name: 'Belarussian Ruble', alpha_code: 'BYR', numeric_code: 974
Currency.register english_name: 'Belize Dollar', alpha_code: 'BZD', numeric_code: 84
Currency.register english_name: 'CFA Franc BCEAO', alpha_code: 'XOF', numeric_code: 952
Currency.register english_name: 'Bermudian Dollar', alpha_code: 'BMD', numeric_code: 60
Currency.register english_name: 'Ngultrum', alpha_code: 'BTN', numeric_code: 64
Currency.register english_name: 'Indian Rupee', alpha_code: 'INR', numeric_code: 356
Currency.register english_name: 'Boliviano', alpha_code: 'BOB', numeric_code: 68
Currency.register english_name: 'Mvdol', alpha_code: 'BOV', numeric_code: 984
Currency.register english_name: 'Convertible Mark', alpha_code: 'BAM', numeric_code: 977
Currency.register english_name: 'Pula', alpha_code: 'BWP', numeric_code: 72
Currency.register english_name: 'Norwegian Krone', alpha_code: 'NOK', numeric_code: 578
Currency.register english_name: 'Brazilian Real', alpha_code: 'BRL', numeric_code: 986
Currency.register english_name: 'Brunei Dollar', alpha_code: 'BND', numeric_code: 96
Currency.register english_name: 'Bulgarian Lev', alpha_code: 'BGN', numeric_code: 975
Currency.register english_name: 'Burundi Franc', alpha_code: 'BIF', numeric_code: 108
Currency.register english_name: 'Riel', alpha_code: 'KHR', numeric_code: 116
Currency.register english_name: 'CFA Franc BEAC', alpha_code: 'XAF', numeric_code: 950
Currency.register english_name: 'Canadian Dollar', alpha_code: 'CAD', numeric_code: 124
Currency.register english_name: 'Cape Verde Escudo', alpha_code: 'CVE', numeric_code: 132
Currency.register english_name: 'Cayman Islands Dollar', alpha_code: 'KYD', numeric_code: 136
Currency.register english_name: 'Unidad de Fomento', alpha_code: 'CLF', numeric_code: 990
Currency.register english_name: 'Chilean Peso', alpha_code: 'CLP', numeric_code: 152
Currency.register english_name: 'Yuan Renminbi', alpha_code: 'CNY', numeric_code: 156
Currency.register english_name: 'Colombian Peso', alpha_code: 'COP', numeric_code: 170
Currency.register english_name: 'Unidad de Valor Real', alpha_code: 'COU', numeric_code: 970
Currency.register english_name: 'Comoro Franc', alpha_code: 'KMF', numeric_code: 174
Currency.register english_name: 'Congolese Franc', alpha_code: 'CDF', numeric_code: 976
Currency.register english_name: 'New Zealand Dollar', alpha_code: 'NZD', numeric_code: 554
Currency.register english_name: 'Costa Rican Colon', alpha_code: 'CRC', numeric_code: 188
Currency.register english_name: 'Croatian Kuna', alpha_code: 'HRK', numeric_code: 191
Currency.register english_name: 'Peso Convertible', alpha_code: 'CUC', numeric_code: 931
Currency.register english_name: 'Cuban Peso', alpha_code: 'CUP', numeric_code: 192
Currency.register english_name: 'Netherlands Antillean Guilder', alpha_code: 'ANG', numeric_code: 532
Currency.register english_name: 'Czech Koruna', alpha_code: 'CZK', numeric_code: 203
Currency.register english_name: 'Danish Krone', alpha_code: 'DKK', numeric_code: 208
Currency.register english_name: 'Djibouti Franc', alpha_code: 'DJF', numeric_code: 262
Currency.register english_name: 'Dominican Peso', alpha_code: 'DOP', numeric_code: 214
Currency.register english_name: 'Egyptian Pound', alpha_code: 'EGP', numeric_code: 818
Currency.register english_name: 'El Salvador Colon', alpha_code: 'SVC', numeric_code: 222
Currency.register english_name: 'Nakfa', alpha_code: 'ERN', numeric_code: 232
Currency.register english_name: 'Ethiopian Birr', alpha_code: 'ETB', numeric_code: 230
Currency.register english_name: 'Falkland Islands Pound', alpha_code: 'FKP', numeric_code: 238
Currency.register english_name: 'Fiji Dollar', alpha_code: 'FJD', numeric_code: 242
Currency.register english_name: 'CFP Franc', alpha_code: 'XPF', numeric_code: 953
Currency.register english_name: 'Dalasi', alpha_code: 'GMD', numeric_code: 270
Currency.register english_name: 'Lari', alpha_code: 'GEL', numeric_code: 981
Currency.register english_name: 'Ghana Cedi', alpha_code: 'GHS', numeric_code: 936
Currency.register english_name: 'Gibraltar Pound', alpha_code: 'GIP', numeric_code: 292
Currency.register english_name: 'Quetzal', alpha_code: 'GTQ', numeric_code: 320
Currency.register english_name: 'Pound Sterling', alpha_code: 'GBP', numeric_code: 826
Currency.register english_name: 'Guinea Franc', alpha_code: 'GNF', numeric_code: 324
Currency.register english_name: 'Guyana Dollar', alpha_code: 'GYD', numeric_code: 328
Currency.register english_name: 'Gourde', alpha_code: 'HTG', numeric_code: 332
Currency.register english_name: 'Lempira', alpha_code: 'HNL', numeric_code: 340
Currency.register english_name: 'Hong Kong Dollar', alpha_code: 'HKD', numeric_code: 344
Currency.register english_name: 'Forint', alpha_code: 'HUF', numeric_code: 348
Currency.register english_name: 'Iceland Krona', alpha_code: 'ISK', numeric_code: 352
Currency.register english_name: 'Rupiah', alpha_code: 'IDR', numeric_code: 360
Currency.register english_name: 'SDR (Special Drawing Right)', alpha_code: 'XDR', numeric_code: 960
Currency.register english_name: 'Iranian Rial', alpha_code: 'IRR', numeric_code: 364
Currency.register english_name: 'Iraqi Dinar', alpha_code: 'IQD', numeric_code: 368
Currency.register english_name: 'New Israeli Sheqel', alpha_code: 'ILS', numeric_code: 376
Currency.register english_name: 'Jamaican Dollar', alpha_code: 'JMD', numeric_code: 388
Currency.register english_name: 'Yen', alpha_code: 'JPY', numeric_code: 392
Currency.register english_name: 'Jordanian Dinar', alpha_code: 'JOD', numeric_code: 400
Currency.register english_name: 'Tenge', alpha_code: 'KZT', numeric_code: 398
Currency.register english_name: 'Kenyan Shilling', alpha_code: 'KES', numeric_code: 404
Currency.register english_name: 'North Korean Won', alpha_code: 'KPW', numeric_code: 408
Currency.register english_name: 'Won', alpha_code: 'KRW', numeric_code: 410
Currency.register english_name: 'Kuwaiti Dinar', alpha_code: 'KWD', numeric_code: 414
Currency.register english_name: 'Som', alpha_code: 'KGS', numeric_code: 417
Currency.register english_name: 'Kip', alpha_code: 'LAK', numeric_code: 418
Currency.register english_name: 'Lebanese Pound', alpha_code: 'LBP', numeric_code: 422
Currency.register english_name: 'Loti', alpha_code: 'LSL', numeric_code: 426
Currency.register english_name: 'Rand', alpha_code: 'ZAR', numeric_code: 710
Currency.register english_name: 'Liberian Dollar', alpha_code: 'LRD', numeric_code: 430
Currency.register english_name: 'Libyan Dinar', alpha_code: 'LYD', numeric_code: 434
Currency.register english_name: 'Swiss Franc', alpha_code: 'CHF', numeric_code: 756
Currency.register english_name: 'Lithuanian Litas', alpha_code: 'LTL', numeric_code: 440
Currency.register english_name: 'Pataca', alpha_code: 'MOP', numeric_code: 446
Currency.register english_name: 'Denar', alpha_code: 'MKD', numeric_code: 807
Currency.register english_name: 'Malagasy Ariary', alpha_code: 'MGA', numeric_code: 969
Currency.register english_name: 'Kwacha', alpha_code: 'MWK', numeric_code: 454
Currency.register english_name: 'Malaysian Ringgit', alpha_code: 'MYR', numeric_code: 458
Currency.register english_name: 'Rufiyaa', alpha_code: 'MVR', numeric_code: 462
Currency.register english_name: 'Ouguiya', alpha_code: 'MRO', numeric_code: 478
Currency.register english_name: 'Mauritius Rupee', alpha_code: 'MUR', numeric_code: 480
Currency.register english_name: 'ADB Unit of Account', alpha_code: 'XUA', numeric_code: 965
Currency.register english_name: 'Mexican Peso', alpha_code: 'MXN', numeric_code: 484
Currency.register english_name: 'Mexican Unidad de Inversion (UDI)', alpha_code: 'MXV', numeric_code: 979
Currency.register english_name: 'Moldovan Leu', alpha_code: 'MDL', numeric_code: 498
Currency.register english_name: 'Tugrik', alpha_code: 'MNT', numeric_code: 496
Currency.register english_name: 'Moroccan Dirham', alpha_code: 'MAD', numeric_code: 504
Currency.register english_name: 'Mozambique Metical', alpha_code: 'MZN', numeric_code: 943
Currency.register english_name: 'Kyat', alpha_code: 'MMK', numeric_code: 104
Currency.register english_name: 'Namibia Dollar', alpha_code: 'NAD', numeric_code: 516
Currency.register english_name: 'Nepalese Rupee', alpha_code: 'NPR', numeric_code: 524
Currency.register english_name: 'Cordoba Oro', alpha_code: 'NIO', numeric_code: 558
Currency.register english_name: 'Naira', alpha_code: 'NGN', numeric_code: 566
Currency.register english_name: 'Rial Omani', alpha_code: 'OMR', numeric_code: 512
Currency.register english_name: 'Pakistan Rupee', alpha_code: 'PKR', numeric_code: 586
Currency.register english_name: 'Balboa', alpha_code: 'PAB', numeric_code: 590
Currency.register english_name: 'Kina', alpha_code: 'PGK', numeric_code: 598
Currency.register english_name: 'Guarani', alpha_code: 'PYG', numeric_code: 600
Currency.register english_name: 'Nuevo Sol', alpha_code: 'PEN', numeric_code: 604
Currency.register english_name: 'Philippine Peso', alpha_code: 'PHP', numeric_code: 608
Currency.register english_name: 'Zloty', alpha_code: 'PLN', numeric_code: 985
Currency.register english_name: 'Qatari Rial', alpha_code: 'QAR', numeric_code: 634
Currency.register english_name: 'New Romanian Leu', alpha_code: 'RON', numeric_code: 946
Currency.register english_name: 'Russian Ruble', alpha_code: 'RUB', numeric_code: 643
Currency.register english_name: 'Rwanda Franc', alpha_code: 'RWF', numeric_code: 646
Currency.register english_name: 'Saint Helena Pound', alpha_code: 'SHP', numeric_code: 654
Currency.register english_name: 'Tala', alpha_code: 'WST', numeric_code: 882
Currency.register english_name: 'Dobra', alpha_code: 'STD', numeric_code: 678
Currency.register english_name: 'Saudi Riyal', alpha_code: 'SAR', numeric_code: 682
Currency.register english_name: 'Serbian Dinar', alpha_code: 'RSD', numeric_code: 941
Currency.register english_name: 'Seychelles Rupee', alpha_code: 'SCR', numeric_code: 690
Currency.register english_name: 'Leone', alpha_code: 'SLL', numeric_code: 694
Currency.register english_name: 'Singapore Dollar', alpha_code: 'SGD', numeric_code: 702
Currency.register english_name: 'Sucre', alpha_code: 'XSU', numeric_code: 994
Currency.register english_name: 'Solomon Islands Dollar', alpha_code: 'SBD', numeric_code: 90
Currency.register english_name: 'Somali Shilling', alpha_code: 'SOS', numeric_code: 706
Currency.register english_name: 'South Sudanese Pound', alpha_code: 'SSP', numeric_code: 728
Currency.register english_name: 'Sri Lanka Rupee', alpha_code: 'LKR', numeric_code: 144
Currency.register english_name: 'Sudanese Pound', alpha_code: 'SDG', numeric_code: 938
Currency.register english_name: 'Surinam Dollar', alpha_code: 'SRD', numeric_code: 968
Currency.register english_name: 'Lilangeni', alpha_code: 'SZL', numeric_code: 748
Currency.register english_name: 'Swedish Krona', alpha_code: 'SEK', numeric_code: 752
Currency.register english_name: 'WIR Euro', alpha_code: 'CHE', numeric_code: 947
Currency.register english_name: 'WIR Franc', alpha_code: 'CHW', numeric_code: 948
Currency.register english_name: 'Syrian Pound', alpha_code: 'SYP', numeric_code: 760
Currency.register english_name: 'New Taiwan Dollar', alpha_code: 'TWD', numeric_code: 901
Currency.register english_name: 'Somoni', alpha_code: 'TJS', numeric_code: 972
Currency.register english_name: 'Tanzanian Shilling', alpha_code: 'TZS', numeric_code: 834
Currency.register english_name: 'Baht', alpha_code: 'THB', numeric_code: 764
Currency.register english_name: 'Pa’anga', alpha_code: 'TOP', numeric_code: 776
Currency.register english_name: 'Trinidad and Tobago Dollar', alpha_code: 'TTD', numeric_code: 780
Currency.register english_name: 'Tunisian Dinar', alpha_code: 'TND', numeric_code: 788
Currency.register english_name: 'Turkish Lira', alpha_code: 'TRY', numeric_code: 949
Currency.register english_name: 'Turkmenistan New Manat', alpha_code: 'TMT', numeric_code: 934
Currency.register english_name: 'Uganda Shilling', alpha_code: 'UGX', numeric_code: 800
Currency.register english_name: 'Hryvnia', alpha_code: 'UAH', numeric_code: 980
Currency.register english_name: 'UAE Dirham', alpha_code: 'AED', numeric_code: 784
Currency.register english_name: 'US Dollar (Next day)', alpha_code: 'USN', numeric_code: 997
Currency.register english_name: 'Uruguay Peso en Unidades Indexadas (URUIURUI)', alpha_code: 'UYI', numeric_code: 940
Currency.register english_name: 'Peso Uruguayo', alpha_code: 'UYU', numeric_code: 858
Currency.register english_name: 'Uzbekistan Sum', alpha_code: 'UZS', numeric_code: 860
Currency.register english_name: 'Vatu', alpha_code: 'VUV', numeric_code: 548
Currency.register english_name: 'Bolivar', alpha_code: 'VEF', numeric_code: 937
Currency.register english_name: 'Dong', alpha_code: 'VND', numeric_code: 704
Currency.register english_name: 'Yemeni Rial', alpha_code: 'YER', numeric_code: 886
Currency.register english_name: 'Zambian Kwacha', alpha_code: 'ZMW', numeric_code: 967
Currency.register english_name: 'Zimbabwe Dollar', alpha_code: 'ZWL', numeric_code: 932
Currency.register english_name: 'Bond Markets Unit European Composite Unit (EURCO)', alpha_code: 'XBA', numeric_code: 955
Currency.register english_name: 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', alpha_code: 'XBB', numeric_code: 956
Currency.register english_name: 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', alpha_code: 'XBC', numeric_code: 957
Currency.register english_name: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', alpha_code: 'XBD', numeric_code: 958
Currency.register english_name: 'Gold', alpha_code: 'XAU', numeric_code: 959
Currency.register english_name: 'Palladium', alpha_code: 'XPD', numeric_code: 964
Currency.register english_name: 'Platinum', alpha_code: 'XPT', numeric_code: 962
Currency.register english_name: 'Silver', alpha_code: 'XAG', numeric_code: 961
