apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: ledger
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: db-migrate
          image: evgenymyasishchev/ledger:latest
          args: ["db-setup"]
          env:
            - name: DATABASE_URL
              value: "postgres://ledger:password@postgres.postgres/ledger"
      restartPolicy: Never
  backoffLimit: 4
