development:
  adapter: postgresql
  encoding: unicode
  database: ledger_dev
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: 5432
  username: postgres
  password: password
  pool: 10
  timeout: 10000

production:
  adapter: postgresql
  encoding: unicode
  database: ledger
  pool: 10
  timeout: 10000

test:
  database: ledger_test
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: 5432
  username: postgres
  password: password
  pool: 10
  timeout: 10000
