development:
  adapter: postgresql
  encoding: unicode
  database: ledger_dev
  host: localhost
  port: 5432
  username: postgres
  pool: 10
  timeout: 10000

production:
  adapter: postgresql
  encoding: unicode
  database: ledger
  pool: 10
  timeout: 10000

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  pool: 10
  timeout: 10000
