development:
  adapter: postgresql
  encoding: unicode
  database: ledger_dev
  pool: 10
  timeout: 10000

production:
  adapter: postgresql
  encoding: unicode
  database: ledger
  pool: 10
  timeout: 10000

test:
  adapter: postgresql
  encoding: unicode
  database: ledger_test
  pool: 10
  timeout: 10000