# To use this config set env DB_CONFIG=config/database_postgres.yml

development: 
  adapter: postgresql
  encoding: unicode
  database: ledger_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ledger_test
  pool: 5
  
# Using independent event store database to avoid schema polution in dev env
event-store:
  adapter: postgres
  encoding: unicode
  database: ledger_event_store
  pool: 5
  timeout: 5000
