apiVersion: v1
kind: Namespace
metadata:
  name: registry

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5000
              hostPort: 5000
      nodeSelector:
        registry: "true"
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: registry
spec:
  ports:
    - port: 5000
  selector:
    app: registry

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "localhost:5000"
    hostFromContainerRuntime: "ledger-worker:5000"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
