name: Test

on:
  push

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Local Registry
      uses: actions/cache@v2
      with:
        path: tmp/local-registry
        key: ${{ runner.os }}-local-registry-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-local-registry-

    - name: Debug Before
      run: |
        ls -l
        ls -l tmp
        ls -l tmp/local-registry/docker/registry/v2/repositories/
        ls -l tmp/local-registry/docker/registry/v2/blobs/sha256/
        du -d 1 -h tmp/local-registry/
        curl -X GET localhost:5000/v2/_catalog
        curl -X GET localhost:5000/v2/ledger-cache/tags/list

    - name: Build service containers
      run: docker-compose build beanstalkd

    - name: Start dependencies
      run: docker-compose up -d db beanstalkd registry

    - name: Build local image
      run: make ledger-local-dev-image

    - name: Debug After
      run: |
        ls -l
        ls -l tmp
        ls -l tmp/local-registry/docker/registry/v2/repositories/
        ls -l tmp/local-registry/docker/registry/v2/blobs/sha256/
        du -d 1 -h tmp/local-registry/
        curl -X GET localhost:5000/v2/_catalog
        curl -X GET localhost:5000/v2/ledger-cache/tags/list

    - name: Do db setup
      run: docker-compose run --rm app bash -c "rake db:setup"

    - name: Run tests
      run: docker-compose run --rm app bash -c "rspec spec"

    - name: Dump db logs
      if: failure()
      run: docker-compose logs db

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down