name: Test

on:
  push

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build containers
      run: docker-compose build

    - name: Start dependencies
      run: docker-compose up -d db beanstalkd

    - name: Do db setup
      run: docker-compose run --rm app bash -c "rake db:setup"

    - name: Run tests
      run: docker-compose run --rm app bash -c "rspec spec"

    - name: Dump db logs
      if: failure()
      run: docker-compose logs db

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down